# -*- coding: utf-8 -*-
"""CNN_FinalProject_Piano_Roll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGwlDJOPqPa1UMKsyAITmTRS5osdhGOJ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from pathlib import Path

train_csv_path = Path("/content/drive/MyDrive/data/splits/train.csv") # Path to the train manifest
cnn_data_root = Path("/content/drive/MyDrive/data/processed/cnn") # Root directory for CNN npy files

df = pd.read_csv(train_csv_path)
print(f"Original row count in CSV: {len(df)}")

def file_exists(row, data_root):
    stem = Path(row['filename']).stem
    full_path = data_root / row['composer'] / f"{stem}.npy"
    return full_path.exists()

# Filter out rows where the file does not exist on disk
# Apply the function row-wise using apply with axis=1
df['exists'] = df.apply(lambda row: file_exists(row, cnn_data_root), axis=1)
df_clean = df[df['exists']].drop(columns=['exists'])

print(f"Cleaned row count: {len(df_clean)}")
print(f"Removed {len(df) - len(df_clean)} missing file references.")

# Save back to CSV
df_clean.to_csv(train_csv_path, index=False)

from pathlib import Path
import os
import pandas as pd
import numpy as np

# Set this to your OUT_DIR path
OUT_DIR = Path("/content/drive/MyDrive/data/processed")  # update if your path differs

corrupt_paths = []

print("Scanning for corrupt or empty .npy files...")
for npy_file in OUT_DIR.rglob("*.npy"):
    try:
        # Check if 0 bytes or unreadable by numpy
        if npy_file.stat().st_size == 0:
            raise EOFError("0-byte file")

        # Test loading the file array
        _ = np.load(npy_file)

    except Exception as e:
        print(f"Removing corrupt file ({e}): {npy_file.name}")
        corrupt_paths.append(str(npy_file))
        os.remove(npy_file)

print(f"Done! Cleaned up {len(corrupt_paths)} corrupted files.")

train_csv_path = OUT_DIR.parent / "train.csv"
if train_csv_path.exists():
    df_train = pd.read_csv(train_csv_path)

    # Keep only rows where the file actually exists on disk
    initial_count = len(df_train)
    df_train['full_path'] = df_train['npy_path'].apply(lambda p: str(OUT_DIR.parent.parent / p))
    df_train = df_train[df_train['full_path'].apply(lambda p: Path(p).exists())]
    df_train = df_train.drop(columns=['full_path'])

    df_train.to_csv(train_csv_path, index=False)
    print(f"Updated train.csv: dropped {initial_count - len(df_train)} missing rows. New total: {len(df_train)}")

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from pathlib import Path

class PianoRollDataset(Dataset):
    def __init__(self, manifest_path, data_dir, window_size=120):
        self.df = pd.read_csv(manifest_path)
        self.data_dir = Path(data_dir)
        self.window_size = window_size

        # Automatically map composer names to integer labels (0 to 3)
        self.composers = sorted(self.df['composer'].unique())
        self.label_map = {name: idx for idx, name in enumerate(self.composers)}

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        stem = Path(row['filename']).stem
        npy_path = self.data_dir / row['composer'] / f"{stem}.npy"

        roll = np.load(npy_path)

        time_steps = roll.shape[1]
        if time_steps >= self.window_size:
            start_idx = np.random.randint(0, time_steps - self.window_size + 1)
            window = roll[:, start_idx : start_idx + self.window_size]
        else:
            pad_amount = self.window_size - time_steps
            window = np.pad(roll, ((0, 0), (0, pad_amount)), mode='constant')


        window = window.astype(np.float32) / 127.0

        window = np.expand_dims(window, axis=0)

        label = self.label_map[row['composer']]

        return torch.tensor(window), torch.tensor(label, dtype=torch.long)

SPLITS_DIR = "/content/drive/MyDrive/data/splits"
CNN_DIR = "/content/drive/MyDrive/data/processed/cnn"

# Create the dataset
train_dataset = PianoRollDataset(
    manifest_path=f"{SPLITS_DIR}/train.csv",
    data_dir=CNN_DIR,
    window_size=120
)

# Create the data loader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Test the output shape
for images, labels in train_loader:
    print(f"Batch Image Shape: {images.shape}") # Should be [32, 1, 88, 120]
    print(f"Batch Label Shape: {labels.shape}") # Should be [32]
    break

import numpy as np
import matplotlib.pyplot as plt

roll = np.load("/content/drive/MyDrive/data/processed/cnn/bach/003706b_.npy")

print(roll)
print(f"Dimensions: {roll.shape}")

plt.imshow(roll, aspect='auto', origin='lower', cmap='magma')
plt.title("Piano Roll Visualization")
plt.ylabel("Pitch (88 Keys)")
plt.xlabel("Time Steps")
plt.colorbar(label="Velocity (Volume)")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

splits = ['train', 'val', 'test']
raw_composers = ['bach', 'beethoven', 'chopin', 'mozart'] # Lowercase as they appear in CSV
composer_classes = ['Bach', 'Beethoven', 'Chopin', 'Mozart']
lower_to_cap_map = dict(zip(raw_composers, composer_classes))

plot_data = []

print("=" * 40)
print("DATASET DISTRIBUTION REPORT")
print("=" * 40)

for split in splits:
    csv_path = f"{SPLITS_DIR}/{split}.csv"
    df = pd.read_csv(csv_path)
    total_samples = len(df)

    counts = df['composer'].value_counts().reindex(raw_composers, fill_value=0)

    counts.index = counts.index.map(lower_to_cap_map)

    print(f"\n--- {split.upper()} SET ({total_samples} total chunks) ---")

    for composer, count in counts.items():
        percentage = (count / total_samples) * 100 if total_samples > 0 else 0
        print(f"{composer}: {count} chunks ({percentage:.1f}%)")

        plot_data.append({
            'Dataset': split.capitalize(),
            'Composer': composer,
            'Count': count
        })

df_plot = pd.DataFrame(plot_data)

plt.figure(figsize=(12, 6))
sns.barplot(
    data=df_plot,
    x='Composer',
    y='Count',
    hue='Dataset',
    palette='magma'
)

plt.title('Composer Distribution Across Train, Val, and Test Sets', fontsize=14, fontweight='bold', pad=15)
plt.ylabel('Number of 30-Second Chunks', fontsize=12, fontweight='bold')
plt.xlabel('Composer', fontsize=12, fontweight='bold')
plt.legend(title='Data Split')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

import pandas as pd
from torch.utils.data import DataLoader

df_val = pd.read_csv(f"{SPLITS_DIR}/val.csv")

val_dataset = PianoRollDataset(
    manifest_path=f"{SPLITS_DIR}/val.csv",
    data_dir=CNN_DIR,
    window_size=120
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

print(f"Validation set loaded with {len(val_dataset)} samples.")

"""## Model ##"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class ComposerCNN(nn.Module):
  def __init__(self, num_classes=4, dropout_rate=0.5):
    super(ComposerCNN, self).__init__()

    self.conv1 = nn.Conv2d(1, 16, kernel_size=(12,1), padding=1)
    self.bn1 = nn.BatchNorm2d(16)
    self.pool1 = nn.MaxPool2d(kernel_size=(2,2))

    self.conv2 = nn.Conv2d(16, 32, kernel_size=(1,16), padding=1)
    self.bn2 = nn.BatchNorm2d(32)
    self.pool2 = nn.MaxPool2d(kernel_size=(2,2))

    self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
    self.bn3 = nn.BatchNorm2d(64)
    self.pool3 = nn.MaxPool2d(kernel_size=(2,2))

    self.conv4 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
    self.bn4 = nn.BatchNorm2d(128)
    self.pool4 = nn.MaxPool2d(2, 2)

    self.dropout=nn.Dropout(dropout_rate)

    self.flattened_size = 128 * 5 * 6

    self.fc1 = nn.Linear(self.flattened_size, 256)
    self.bn5 = nn.BatchNorm1d(256)
    self.fc2 = nn.Linear(256, num_classes)

  def forward(self, x):
    x = self.pool1(F.relu(self.bn1(self.conv1(x))))
    x = self.pool2(F.relu(self.bn2(self.conv2(x))))
    x = self.pool3(F.relu(self.bn3(self.conv3(x))))
    x = self.pool4(F.relu(self.bn4(self.conv4(x))))

    x = x.view(-1, self.flattened_size)

    x = F.relu(self.bn5(self.fc1(x)))
    x = self.dropout(x)
    x = self.fc2(x)
    return x

if __name__ == "__main__":
  model = ComposerCNN()

  dummy_input=torch.randn(32,1,88,120)

  model=ComposerCNN(num_classes=4)
  output=model(dummy_input)

  print(output.shape)

"""## Calculate Weights and Train/Val ##"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.utils.class_weight import compute_class_weight

print("Calculating class weights from the training set...")

df_train = pd.read_csv(f"{SPLITS_DIR}/train.csv")

y_train = df_train['composer'].values
unique_classes = np.unique(y_train)

weights = compute_class_weight(class_weight='balanced', classes=unique_classes, y=y_train)

composer_classes = ['Bach', 'Beethoven', 'Chopin', 'Mozart']
for composer, weight in zip(composer_classes, weights):
    print(f"{composer} Weight: {weight:.4f}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights_tensor = torch.tensor(weights, dtype=torch.float).to(device)

import copy
import torch

class EarlyStopping:

    def __init__(self, patience=10, min_delta=0.0):

        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_loss = float('inf')
        self.early_stop = False
        self.best_model_weights = None

    def __call__(self, val_loss, model):
        if val_loss < (self.best_loss - self.min_delta):
            self.best_loss = val_loss
            self.best_model_weights = copy.deepcopy(model.state_dict())
            self.counter = 0
        else:
            self.counter += 1
            print(f"--> EarlyStopping counter: {self.counter} out of {self.patience}")
            if self.counter >= self.patience:
                self.early_stop = True

    def restore_best_weights(self, model):
        """Reloads the best saved weights back into the model."""
        if self.best_model_weights is not None:
            model.load_state_dict(self.best_model_weights)
            print("Successfully restored best model weights from peak epoch!")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on device: {device}")

model = ComposerCNN(num_classes=4).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 30
early_stopper = EarlyStopping(patience=10, min_delta=0.001)

print("Starting Training & Validation with Early Stopping...")

for epoch in range(epochs):

    model.train()
    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for batch_idx, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)


        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

    epoch_train_loss = train_loss / len(train_loader)
    epoch_train_acc = 100. * train_correct / train_total

    model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    epoch_val_loss = val_loss / len(val_loader)
    epoch_val_acc = 100. * val_correct / val_total

    print(f"Epoch [{epoch+1:02d}/{epochs}] | "
          f"Train Loss: {epoch_train_loss:.4f} - Train Acc: {epoch_train_acc:.2f}% | "
          f"Val Loss: {epoch_val_loss:.4f} - Val Acc: {epoch_val_acc:.2f}%")

    early_stopper(epoch_val_loss, model)
    if early_stopper.early_stop:
        print(f"\n[Early Stopping] Triggered at epoch {epoch+1}. Stopping training!")
        break

early_stopper.restore_best_weights(model)
print("Finished Training!")

print(early_stopper.best_loss)

"""## Eval against Test data ##"""

from torch.utils.data import DataLoader

print("Loading test dataset...")

test_dataset = PianoRollDataset(
    manifest_path=f"{SPLITS_DIR}/test.csv",
    data_dir=CNN_DIR,
    window_size=120
)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

model.eval()

test_loss = 0.0
correct = 0
total = 0

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        test_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

avg_test_loss = test_loss / len(test_loader)
test_acc = 100. * correct / total

print("=" * 40)
print(f"TEST RESULTS | Loss: {avg_test_loss:.4f} | Accuracy: {test_acc:.2f}%")
print("=" * 40)

import numpy as np
from sklearn.metrics import classification_report
classification_report = classification_report(all_labels, all_preds, target_names=composer_classes)
print(classification_report)

import torch

# Define the path where you want to save the model
save_path = "/content/drive/MyDrive/data/composer_cnn_weights.pth"

# Save the model's learned weights
torch.save(model.state_dict(), save_path)

print(f"Model successfully saved to {save_path}!")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

composer_classes = ['Bach', 'Beethoven', 'Chopin', 'Mozart']

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(10, 8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=composer_classes,
    yticklabels=composer_classes
)

plt.xlabel('Predicted Composer', fontsize=12, fontweight='bold')
plt.ylabel('True Composer', fontsize=12, fontweight='bold')
plt.title('Composer Classification Confusion Matrix', fontsize=14, pad=20)

plt.show()

"""## Hyperparameterize the model for best performance ##"""

!pip install optuna

import optuna
import torch
import torch.nn as nn
import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
def objective(trial):
    lr = trial.suggest_float("lr", 1e-4, 1e-1, log=True)
    dropout_rate = trial.suggest_float("dropout_rate", 0.2, 0.6)

    model = ComposerCNN(num_classes=4).to(device)

    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

    epochs = 10

    for epoch in range(epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    val_acc = 100. * correct / total


    trial.report(val_acc,epoch)

    if trial.should_prune():
        raise optuna.exceptions.TrialPruned()

    return val_acc

# Create a study object
pruner=optuna.pruners.MedianPruner(n_startup_trials=5,n_warmup_steps=5)
study = optuna.create_study(direction="maximize")

# Run the optimization for a set number of trials
print("Starting Hyperparameter Optimization...")
study.optimize(objective, n_trials=20)

# Print the best results
print("\nBest trial:")
trial = study.best_trial

print(f"  Validation Accuracy: {trial.value:.2f}%")
print("  Best Hyperparameters: ")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

"""## Train against optimized parameters ##"""

import torch
import torch.nn as nn
import torch.optim as optim

print("=" * 40)
print("TRAINING FINAL OPTIMIZED MODEL")
print("=" * 40)

best_lr = study.best_params['lr']


print(f"Using Optimal Learning Rate: {best_lr:.5f}")

final_model = ComposerCNN(num_classes=4).to(device)

optimizer = optim.Adam(final_model.parameters(), lr=best_lr)
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

final_epochs = 30

for epoch in range(final_epochs):

    final_model.train()
    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = final_model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

    epoch_train_loss = train_loss / len(train_loader)
    epoch_train_acc = 100. * train_correct / train_total

    final_model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = final_model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    epoch_val_loss = val_loss / len(val_loader)
    epoch_val_acc = 100. * val_correct / val_total

    print(f"Epoch [{epoch+1:02d}/{final_epochs}] | "
          f"Train Acc: {epoch_train_acc:.2f}% | Val Acc: {epoch_val_acc:.2f}%")

save_path = f"{CNN_DIR}/optimized_composer_cnn.pth"
torch.save(final_model.state_dict(), save_path)

print("=" * 40)
print(f"Model successfully saved to {save_path}!")
print("=" * 40)

import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

model_path = "/content/drive/MyDrive/data/processed/cnn/optimized_composer_cnn.pth"
print(f"Loading optimized model from: {model_path}")

loaded_model = ComposerCNN(num_classes=4).to(device)

loaded_model.load_state_dict(torch.load(model_path))

loaded_model.eval()

print("Evaluating loaded model on test set...")

test_loss = 0.0
correct = 0
total = 0

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = loaded_model(images)
        loss = criterion(outputs, labels)

        test_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

avg_test_loss = test_loss / len(test_loader)
test_acc = 100. * correct / total

print("=" * 40)
print(f"FINAL TEST RESULTS (Optimized Model) | Loss: {avg_test_loss:.4f} | Accuracy: {test_acc:.2f}%")
print("=" * 40)

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=composer_classes,
    yticklabels=composer_classes
)
plt.xlabel('Predicted Composer', fontsize=12, fontweight='bold')
plt.ylabel('True Composer', fontsize=12, fontweight='bold')
plt.title('Optimized Model Confusion Matrix on Test Set', fontsize=14, pad=20)
plt.show()

from sklearn.metrics import classification_report

report = classification_report(all_labels, all_preds, target_names=composer_classes)

print("\nClassification Report (Optimized Model on Test Set):\n")
print(report)

import torch

# Define the path to save the entire model (architecture + weights)
save_path_full_model = "/content/drive/MyDrive/data/processed/cnn/optimized_composer_cnn_full_model.pth"

# Save the entire model
torch.save(final_model, save_path_full_model)

print(f"Entire optimized model (architecture + weights) saved to: {save_path_full_model}")

# To load it later:
# loaded_full_model = torch.load(save_path_full_model)
# loaded_full_model.eval()